### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by andreichalapco** [cormullion/Karnak.jl#21]
Hi great package for drawing graphs ... Is there a quick way for directed graphs to be plotted without arrows? (graph makie has the functionality for `arrow_show=false`, but this package has not this particular API.

**Comment by andreichalapco** [comment]
saw this:

```julia
edgefunction=(k, s, d, f, t) -> draw_edge(f, t),
```

and solves problem.

**Comment by cormullion** [comment]
Yes I should probably fix this one day!
